
name: CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: maven

    - name: Build
      run: mvn -B -U -DskipTests=true package

    - name: Tests
      run: mvn -B -U -Dmaven.test.failure.ignore=true test

    - name: Tests Report
      uses: dorny/test-reporter@v1.6.0
      if: always()
      with:
        name: 'Tests Report'
        path: '**/target/surefire-reports/TEST-*.xml'
        reporter: 'java-junit'
        fail-on-error: true

    - name: SonarCloud Scan
      run: >
        mvn -B -U
        -Dsonar.host.url=${{ vars.SONAR_URL }}
        -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
        -Dsonar.projectKey=${{ vars.SONAR_ORGANIZATION }}_gh-actions-sandbox
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        clean install sonar:sonar

    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v3
      with:
        path: '**/target/*.jar'
        retention-days: 90
