
name: CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: maven

    - name: Build
      run: mvn -B -U -DskipTtests=true package

    - name: Test
      run: mvn -B -U -Dmaven.test.failure.ignore=true test

    - name: Test Report
      uses: dorny/test-reporter@v1.6.0
      if: always()
      with:
        name: 'Tests Report'
        path: '**/target/surefire-reports/TEST-*.xml'
        reporter: 'java-junit'
        fail-on-error: true
