
name: Build

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: maven
    - name: Build with Maven
      run: mvn -B -U package
    - name: Test Reporter
      uses: dorny/test-reporter@v1.6.0
      with:
        name: 'Tests Report'
        path: 'target/surefire-reports/TEST-*.xml'
        reporter: 'java-junit'
