
name: CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: maven

    - name: Build
      run: mvn -B -U -DskipTests=true package

    - name: Tests
      run: mvn -B -U -Dmaven.test.failure.ignore=true test

    - name: Tests Report
      uses: dorny/test-reporter@v1.6.0
      if: always()
      with:
        name: 'Tests Report'
        path: '**/target/surefire-reports/TEST-*.xml'
        reporter: 'java-junit'
        fail-on-error: true

    - name: SonarCloud Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: >
        mvn -B -U
        -Dsonar.host.url=${{ vars.SONAR_URL }}
        -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
        -Dsonar.projectKey=${{ vars.SONAR_ORGANIZATION }}_gh-actions-sandbox
        clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v3
      with:
        path: '**/target/*.jar'
        retention-days: 90
